[workspace]
resolver = "2"
members = ["ctltool", "windows-ctl"]

[workspace.metadata.release]
publish = false
push = true
consolidate-commits = false
pre-release-commit-message = "{{crate_name}}: {{version}}"
