[package]
name = "windows-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
cab = { version = "0.4.1", optional = true }
der = { path = "../formats/der", features = ["std"] }
hex = "0.4"
thiserror = "1.0"
pkcs7 = { path = "../formats/pkcs7" }
